
DROP TABLE IF EXISTS DENEME;
CREATE DATABASE deneme;

CREATE TABLE kayit(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    isim VARCHAR (50) NOT NULL,
    soyisim VARCHAR (50) NOT NULL,
    tc VARCHAR (50) NOT NULL,
    tel VARCHAR (50) NOT NULL,
    email VARCHAR (50) NOT NULL,
    sifre VARCHAR (50) NOT NULL,
    dogum_tarihi DATE; 
);